services:

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "5173:80"
    networks:
      - donaton-network
    depends_on:
      - bff-service

  bff-service:
    build: ./bff-service
    container_name: bff-service
    ports:
      - "8080:8080"
    networks:
      - donaton-network
    depends_on:
      - auth-service
      - users-service
      - donations-service
      - inventory-service
      - logistic-service
      
      # Variables de entorno para URLs internas de los microservicios (DOCKER COMPOSE)
    environment:
      - SERVICES_AUTH_URL=http://auth-service:8081
      - SERVICES_USERS_URL=http://users-service:8082
      - SERVICES_DONATIONS_URL=http://donations-service:8083
      - SERVICES_INVENTORY_URL=http://inventory-service:8084
      - SERVICES_LOGISTIC_URL=http://logistic-service:8085

  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - donaton-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:donaton_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true

  users-service:
    build: ./users-service
    container_name: users-service
    networks:
      - donaton-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:users_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=

  donations-service:
    build: ./donations-service
    container_name: donations-service
    networks:
      - donaton-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:donations_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    networks:
      - donaton-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inventory_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=

  logistic-service:
    build: ./logistic-service
    container_name: logistic-service
    networks:
      - donaton-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:logistic_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=

networks:
  donaton-network:
    driver: bridge

  # Futura base de datos (Comentar/Descomentar según se necesite)
  # db:
  #   image: postgres:16
  #   container_name: donaton-db
  #   environment:
  #     POSTGRES_DB: donaton_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports: