services:

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "5173:80"
    networks:
      - donaton-network
    depends_on:
      - bff-service

  bff-service:
    build: ./bff-service
    container_name: bff-service
    ports:
      - "8080:8080"
    networks:
      - donaton-network
    depends_on:
      - auth-service
      - profile-service
      - donations-service
      - inventory-service
      - logistic-service
      
      # Variables de entorno para URLs internas de los microservicios (DOCKER COMPOSE)
    environment:
      - SERVICES_AUTH_URL=http://auth-service:8081
      - SERVICES_PROFILE_URL=http://profile-service:8082
      - SERVICES_DONATIONS_URL=http://donations-service:8083
      - SERVICES_INVENTORY_URL=http://inventory-service:8084
      - SERVICES_LOGISTIC_URL=http://logistic-service:8085

  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - donaton-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auth_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  profile-service:
    build: ./profile-service
    container_name: profile-service
    networks:
      - donaton-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/profile_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  donations-service:
    build: ./donations-service
    container_name: donations-service
    networks:
      - donaton-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/donations_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    networks:
      - donaton-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inventory_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  logistic-service:
    build: ./logistic-service
    container_name: logistic-service
    networks:
      - donaton-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/logistic_db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:16
    container_name: donaton-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - donaton-network
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  donaton-network:
    driver: bridge